baseURL = "/"
title = "Ghost Basenji"
theme = "anatole"

[params]
title = "I'm Ghost Basenji"
author = "Ghost Basenji"
description = "Notes of a novice programmer"
profilePicture = "/images/profile.png"
copyright = "GhostBasenji 2022-{{ YEAR }}"
displayMode = "light"
disableThemeSwitcher = true # Theme switcher is enabled by default
doNotLoadAnimations = true # Animations are loaded by default

singleDateFormat = "Mon, Jan 2, 2006"
indexDateFormat = "Mon, Jan 2, 2006"
listDateFormat = "Jan 2"

contentratio = 0.75

readMore = true


## Math settings
[params.math]
enable = false  # options: true, false. Enable math support globally, default: false. You can always enable math on per page.
use = "katex"  # options: "katex", "mathjax". default is "katex".

# Syntax highlighting
pygmentsUseClasses = false
pygmentsCodeFences = true
pygmentsCodefencesGuessSyntax = true

[markup]
  [markup.highlight]
    style = "vs"

[[params.socialIcons]]
icon = "fab fa-telegram"
title = "telegram"
url = "https://t.me/ghostbasenji"

[[params.socialIcons]]
icon = "fas fa-envelope"
title = "e-mail"
url = "mailto:petr.and.vic@gmail.com"

[taxonomies]
  category = "categories"
  # series = "series"
  tag = "tags"

## Menu items
[menu]

  [[menu.main]]
  name = "Главная"
  identifier = "home"
  weight = 100
  url = "/"

  [[menu.main]]
  name = "Архив"
  weight = 200
  identifier = "post"
  url = "/post/"

  ## [[menu.main]]
  ## name = "Теги"
  ## weight = 300
  ## identifier = "tag"
  ## url = "/tags/"

  [[menu.main]]
  name = "Мои проекты"
  weight = 400
  identifier = "myprojects"
  url = "/myprojects/"

  [[menu.main]]
  name = "About"
  weight = 500
  identifier = "about"
  url = "/about/"

  ## [[menu.main]]
  ## name = "Категории"
  ## weight = 300
  ## identifier = "categories"
  ## url = "/categories/"
